baseURL = "https://lewisay.com/"
languageCode = "en-us"
title = "^_^"
theme = "anatole"

[params]
author = "lewisay"
description = "心游于艺，道不远人"
profilePicture = "images/profile.jpeg"
customCss = ["css/index.css"]